### ISSUE TITLE
DENSE dataset, does it have Radar data?

### ISSUE THREAD

**Issue by soyebn** [ZHOUYI1023/awesome-radar-perception#5]
Wonderful compilation of Radar related datasets. I could not find any information on Radar for DENSE dataset of ULM. It does not have Radar data, right?

**Comment by ZHOUYI1023** [comment]
DENSE is a big project. The radar-related dataset is used in the paper "seeing through fog xxx". You can fill this registration form. Then, they will send you the link. You can find the radar data inside a file called "seeing through fog".
https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets/dense-registration-form/

**Comment by soyebn** [comment]
Thanks a lot.
